// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzmPfM4TgSR-wL4jlEMigzHDiwTI4Kkd4',
    appId: '1:230366956339:web:d28de30a345bab406b0c46',
    messagingSenderId: '230366956339',
    projectId: 'todolistfirebase-ec74b',
    authDomain: 'todolistfirebase-ec74b.firebaseapp.com',
    storageBucket: 'todolistfirebase-ec74b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZyqWDXBOyzenVUxh4goJwhmJjGIMnwnU',
    appId: '1:230366956339:android:38e23fdd4e233dad6b0c46',
    messagingSenderId: '230366956339',
    projectId: 'todolistfirebase-ec74b',
    storageBucket: 'todolistfirebase-ec74b.appspot.com',
  );
}
